---
title: Template of MSF situation report
author: "Amrish Baidjoe, Thibaut Jombart, and the MSF crew"
date: "2018-04-17"
output:
  html_document:
    toc: true
    toc_depth: 2
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}

library(knitr)
opts_chunk$set(collapse = TRUE, dev = "png")

```

# Installing packages
```{r install_pkgs}
#only required for new Rstudio installations
install.packages("epitrix")
install.packages("tidyverse")
install.packages("here")
install.packages("incidence")
install.packages("ggplot2")

```

# Loading packages for session

```{r load_pkgs}

library(tidyverse)
library(here)
library(incidence)
library(ggplot2)
library(epitrix)


```

# Loading data

```

```


```{r load_data}

file <- here("data/xlsx/fake_ncd_export_final.xlsx")
dat <- as.data.frame(readxl::read_xlsx(file), stringsAsFactor = FALSE)

dim(dat)
head(dat)

```


We fix the dates and make sure they are stored as `Date` objects:

```{r fix-dates}

for (i in seq_len(ncol(dat))) {
  if (inherits(dat[, i], "POSIXct")) {
    dat[, i]  <- as.Date(dat[, i])
  } 
}

```



# Basic epicurve

```{r incidence-curve}

i <- incidence(dat$"Admission date")
plot(i)

```
